Backend: Vivado
Board: null
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 16384
    Strategy: Resource
IOType: io_stream
InputData: null
KerasModel: !keras_model 'Deepcalo_model_full_final/keras_model.h5'
OutputDir: Deepcalo_model_full_final
OutputPredictions: null
ProjectName: myproject
Stamp: FF8Bd17D
XilinxPart: xczu9eg-ffvb1156-2-e
